# Generated by Django 2.2.5 on 2020-07-29 12:39

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_userinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='items',
        ),
        migrations.AddField(
            model_name='orders',
            name='no_of_items',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Booked', 'Booked'), ('Delivered', 'Delivered')], default='Pending', max_length=12),
        ),
        migrations.AddField(
            model_name='orders',
            name='pub_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 29, 12, 39, 32, 324823, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='orders',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='phone',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[6-9]{1}[0-9]{9}$', 'Enter a valid mobile number')]),
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='shop.Orders')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='shop.Product')),
            ],
        ),
    ]
