# Generated by Django 2.2.5 on 2020-07-29 12:47

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200729_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[6-9]{1}[0-9]{9}$', 'Enter a valid mobile number')]),
        ),
        migrations.AlterField(
            model_name='orders',
            name='pub_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 29, 12, 47, 15, 233818, tzinfo=utc)),
        ),
    ]
