# Generated by Django 2.2.5 on 2020-07-30 02:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200729_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_order', to='shop.UserInfo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='pub_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
